default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: jeuxolympiques
  host: localhost

development:
  <<: *default
  database: greetings_development

test:
  <<: *default
  database: greetings_test

production:
  <<: *default
  database: greetings_production