Greeting.create!(message: 'Hello, world!')
Greeting.create!(message: 'Hello, Rails!')
Greeting.create!(message: 'Hello, Ruby!')
Greeting.create!(message: 'Hello, PostgreSQL!')
Greeting.create!(message: 'Hello, Heroku!')
Greeting.create!(message: 'Hello, Docker!')